name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  nix:
    runs-on: ubuntu-latest
    name: Nix & chezmoi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Add Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Chezmoi apply
        run: |
          # bitwarden と連携しているファイルは CI では除外する
          echo ".ssh/*" >> home/.chezmoiignore.tmpl
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply -S .
      - name: Check Nixpkgs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Check the flake
        run: nix flake check && nix run home-manager/master -- build --flake .#gin
